// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file payloadPublisher.cpp
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#include "payloadPublisher.h"
#include "payloadPubSubTypes.h"
#include "security/SecurityConfig.h"

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>

#include <stdexcept>
#include <thread>
#include <chrono>

using namespace eprosima::fastdds::dds;

payloadPublisher::payloadPublisher()
    : participant_(nullptr)
    , publisher_(nullptr)
    , topic_(nullptr)
    , writer_(nullptr)
    , type_(new PayloadPubSubType())
{
}

payloadPublisher::~payloadPublisher()
{
    if (writer_ != nullptr)
    {
        publisher_->delete_datawriter(writer_);
    }
    if (publisher_ != nullptr)
    {
        participant_->delete_publisher(publisher_);
    }
    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
    }
    DomainParticipantFactory::get_instance()->delete_participant(participant_);
}

bool payloadPublisher::init(const std::string& escenario)
{
    // -------------------------------------------------------------------------
    // Configurar el QoS del DomainParticipant.
    // Si el escenario es distinto de "none", configure_security_qos inyectará
    // las propiedades de los plugins PKI-DH, Access-Permissions y AES-GCM-GMAC
    // antes de que el participante sea creado por la factoría de FastDDS.
    // Las propiedades de seguridad DEBEN estar presentes en el QoS en el momento
    // de llamar a create_participant(); no pueden añadirse a posteriori.
    // -------------------------------------------------------------------------
    DomainParticipantQos pqos;
    pqos.name("PayloadPublisher");

    try
    {
        // Inyectar los plugins de seguridad según el escenario CLI.
        // "publisher" indica qué certificado e identidad usar:
        //   security/pki/publisher_cert.pem + security/pki/publisher_key.pem
        security::configure_security_qos(pqos, escenario, "publisher");
    }
    catch (const std::invalid_argument& e)
    {
        std::cerr << e.what() << std::endl;
        return false;
    }

    //CREATE THE PARTICIPANT
    participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
    if (participant_ == nullptr)
    {
        std::cerr << "[Publisher] Error al crear el DomainParticipant. "
                  << "Verifica que los artefactos de seguridad existen y que "
                  << "el binario se ejecuta desde la raíz del proyecto." << std::endl;
        return false;
    }

    //REGISTER THE TYPE
    type_.register_type(participant_);

    //CREATE THE PUBLISHER
    publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
    if (publisher_ == nullptr)
    {
        return false;
    }

    //CREATE THE TOPIC
    topic_ = participant_->create_topic(
        "payloadTopic",
        type_.get_type_name(),
        TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        return false;
    }

    // CREATE THE WRITER
    DataWriterQos wqos = DATAWRITER_QOS_DEFAULT;
    wqos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    writer_ = publisher_->create_datawriter(topic_, wqos, &listener_);
    if (writer_ == nullptr)
    {
        return false;
    }

    std::cout << "Payload DataWriter created." << std::endl;
    return true;
}

void payloadPublisher::PubListener::on_publication_matched(
        eprosima::fastdds::dds::DataWriter*,
        const eprosima::fastdds::dds::PublicationMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        std::cout << "DataWriter matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        std::cout << "DataWriter unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for PublicationMatchedStatus current count change" << std::endl;
    }
}

bool payloadPublisher::publish(uint32_t payload_size_bytes, uint32_t sleep_us)
{
    if (listener_.matched > 0)
    {
        Payload st;
        static uint32_t msg_count = 0;

        // 1. Número de secuencia
        st.sequence_number() = ++msg_count; // Asignación directa si es un struct generado

        // 2. Llenar el payload con 'X'
        // Nos aseguramos de redimensionar la secuencia
        st.data().resize(payload_size_bytes);
        for(size_t i = 0; i < payload_size_bytes; ++i)
        {
            st.data()[i] = 'X';
        }

        // 3. Estampar el tiempo de salida en microsegundos justo antes de enviar
        auto now = std::chrono::high_resolution_clock::now();
        auto now_us = std::chrono::time_point_cast<std::chrono::microseconds>(now).time_since_epoch().count();
        st.timestamp_tx() = now_us; // Asignación directa

        // 4. Escribir al bus DDS
        writer_->write(&st);

        // 5. Pausa entre mensajes
        if (sleep_us > 0) {
            std::this_thread::sleep_for(std::chrono::microseconds(sleep_us));
        }

        return true;
    }
    return false;
}
