// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file payloadSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>

#include "payloadSubscriber.h"
#include "payloadPubSubTypes.h"
#include "security/SecurityConfig.h"

#include <chrono>
#include <stdexcept>
#include <iostream>
#include <fstream>
#include <thread>

using namespace eprosima::fastdds::dds;

payloadSubscriber::payloadSubscriber()
    : participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    , type_(new PayloadPubSubType())
{
}

payloadSubscriber::~payloadSubscriber()
{
    if (reader_ != nullptr)
    {
        subscriber_->delete_datareader(reader_);
    }
    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
    }
    if (subscriber_ != nullptr)
    {
        participant_->delete_subscriber(subscriber_);
    }
    DomainParticipantFactory::get_instance()->delete_participant(participant_);
}

bool payloadSubscriber::init(const std::string& escenario)
{
    //CREATE THE PARTICIPANT
    DomainParticipantQos pqos;
    pqos.name("PayloadSubscriber");

    // ── Seguridad DDS-Security ─────────────────────────────────────────────────
    // Inyecta los plugins PKI-DH, Access-Permissions y (si aplica) AES-GCM-GMAC
    // en el QoS del participante ANTES de crearlo. FastDDS lee las propiedades
    // durante la inicialización del participante y no acepta cambios posteriores.
    // Con escenario="none" la función retorna sin modificar pqos.
    try
    {
        security::configure_security_qos(pqos, escenario, "subscriber");
    }
    catch (const std::invalid_argument& e)
    {
        std::cerr << e.what() << std::endl;
        return false;
    }

    participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
    if (participant_ == nullptr)
    {
        std::cerr << "❌ [Error] El participante no pudo ser creado en dominio 0." << std::endl;
        return false;
    }

    //REGISTER THE TYPE
    type_.register_type(participant_);

    //CREATE THE SUBSCRIBER
    subscriber_ = participant_->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr);
    if (subscriber_ == nullptr)
    {
        return false;
    }

    //CREATE THE TOPIC
    topic_ = participant_->create_topic(
        "payloadTopic",
        type_.get_type_name(),
        TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        return false;
    }

    //CREATE THE READER
    DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
    rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
    rqos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
    if (reader_ == nullptr)
    {
        return false;
    }

    return true;
}

void payloadSubscriber::SubListener::on_subscription_matched(
        DataReader*,
        const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        std::cerr << "Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        std::cerr << "Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cerr << info.current_count_change
                  << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void payloadSubscriber::SubListener::on_data_available(
        DataReader* reader)
{
    // Take data
    Payload st;
    SampleInfo info;

    if (reader->take_next_sample(&st, &info) == ReturnCode_t::RETCODE_OK)
    {
        if (info.valid_data)
        {
            auto now = std::chrono::high_resolution_clock::now();
            uint64_t timestamp_rx = std::chrono::time_point_cast<std::chrono::microseconds>(now).time_since_epoch().count();

            // Cálculo de latencia: Tiempo de Recepción - Tiempo de Envío (TX)
            uint64_t latency_us = timestamp_rx - st.timestamp_tx();

            // Salida limpia para tu CSV: SeqNum, PayloadSize, Latency(us)
            std::cout << st.sequence_number() << "," << st.data().size() << "," << latency_us << std::endl;

            samples++;
        }
    }
}

void payloadSubscriber::run()
{
    // CSV header — must be the very first line on stdout
    std::cout << "SeqNum,PayloadBytes,Latency_us" << std::endl;

    // Definimos el límite según tu script (1000 calentamiento + 10000 medición)
    uint32_t n_muestras = 11000;

    std::cerr << "[Subscriber] Listo. Escuchando en 'payloadTopic'..." << std::endl;
    std::cerr << "[Subscriber] Esperando " << n_muestras << " muestras para cerrar..." << std::endl;
    std::cerr << "[Subscriber] Salida CSV -> SeqNum,PayloadBytes,Latency_us" << std::endl;

    // Usamos listener_.samples que es lo que definiste en el .h
    while (listener_.samples < n_muestras)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    std::cerr << "[Subscriber] ¡Prueba completada con éxito!" << std::endl;
    std::cerr << "[Subscriber] Total recibidas: " << listener_.samples << std::endl;
}
