// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file payloadPublisher.h
 * This header file contains the declaration of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _FAST_DDS_GENERATED_PAYLOAD_PUBLISHER_H_
#define _FAST_DDS_GENERATED_PAYLOAD_PUBLISHER_H_

#include <string>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/DataWriterListener.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/topic/TypeSupport.hpp>

class payloadPublisher
{
public:

    payloadPublisher();

    virtual ~payloadPublisher();

    /**
     * @brief Inicializa el participante DDS, publisher, tópico y DataWriter.
     *
     * @param escenario Escenario de seguridad DDS-Security a aplicar.
     *                  Valores: "none" | "auth" | "encrypt" | "access"
     *                  Por defecto "none" (sin seguridad) para compatibilidad
     *                  con el modo de pruebas de línea base.
     * @return true si todos los recursos DDS se crearon correctamente.
     */
    bool init(const std::string& escenario = "none");

    bool publish(uint32_t payload_size_bytes, uint32_t sleep_us);

private:

    eprosima::fastdds::dds::DomainParticipant* participant_;
    eprosima::fastdds::dds::Publisher* publisher_;
    eprosima::fastdds::dds::Topic* topic_;
    eprosima::fastdds::dds::DataWriter* writer_;
    eprosima::fastdds::dds::TypeSupport type_;

    class PubListener : public eprosima::fastdds::dds::DataWriterListener
    {
    public:

        PubListener() = default;

        ~PubListener() override = default;

        void on_publication_matched(
                eprosima::fastdds::dds::DataWriter* writer,
                const eprosima::fastdds::dds::PublicationMatchedStatus& info) override;

        int matched = 0;
    }
    listener_;
};

#endif // _FAST_DDS_GENERATED_PAYLOAD_PUBLISHER_H_
