// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file payloadPubSubMain.cpp
 * This file acts as a main entry point to the application.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include "payloadPublisher.h"
#include "payloadSubscriber.h"
#include <iostream>
#include <string>
#include <thread>
#include <chrono>

int main(int argc, char** argv)
{
    int type = 0;

    // Permitimos más argumentos para el publicador
    if (argc >= 2)
    {
        if (strcmp(argv[1], "publisher") == 0)
        {
            type = 1;
        }
        else if (strcmp(argv[1], "subscriber") == 0)
        {
            type = 2;
        }
    }

    if (type == 0)
    {
        std::cerr << "Error: Argumentos incorrectos." << std::endl;
        std::cerr << "Uso para enviar datos: " << argv[0] << " publisher [muestras] [bytes] [espera_us]" << std::endl;
        std::cerr << "Ejemplo: " << argv[0] << " publisher 5000 1024 1000" << std::endl;
        std::cerr << "Uso para recibir:    " << argv[0] << " subscriber" << std::endl;
        return 1;
    }

    std::cout << "Iniciando nodo DDS..." << std::endl;

    switch (type)
    {
        case 1:
        {
            // Parseo de los parámetros del experimento (con valores por defecto si no se ponen)
            uint32_t samples  = (argc > 2) ? std::stoul(argv[2]) : 1000;
            uint32_t bytes    = (argc > 3) ? std::stoul(argv[3]) : 1024;
            uint32_t sleep_us = (argc > 4) ? std::stoul(argv[4]) : 1000;

            payloadPublisher mypub;
            if (mypub.init())
            {
                std::cout << "Publicador listo. Esperando a que el suscriptor se conecte..." << std::endl;

                // Bucle de espera: no enviamos los datos del experimento hasta que el suscriptor aparezca
                while (!mypub.publish(bytes, sleep_us)) {
                    std::this_thread::sleep_for(std::chrono::milliseconds(100));
                }

                std::cout << "¡Conexión establecida! Enviando " << samples << " muestras de " << bytes << " bytes..." << std::endl;

                // Ya enviamos 1 en el while, mandamos el resto
                for (uint32_t i = 1; i < samples; ++i) {
                    mypub.publish(bytes, sleep_us);
                }

                std::cout << "Envio de datos completado." << std::endl;
                std::this_thread::sleep_for(std::chrono::seconds(1)); // Dar tiempo a que salga el último paquete
            }
            break;
        }
        case 2:
        {
            payloadSubscriber mysub;
            if (mysub.init())
            {
                std::cout << "Suscriptor listo. Imprimiendo CSV: SeqNum, PayloadSize, Latency(us)" << std::endl;
                mysub.run();
            }
            break;
        }
    }

    return 0;
}
