// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file payload.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "payload.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Payload::Payload()
{
    // m_sequence_number com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7cbd213e
    m_sequence_number = 0;
    // m_timestamp_tx com.eprosima.idl.parser.typecode.PrimitiveTypeCode@192d3247
    m_timestamp_tx = 0;
    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@3ecd23d9


}

Payload::~Payload()
{


}

Payload::Payload(
        const Payload& x)
{
    m_sequence_number = x.m_sequence_number;
    m_timestamp_tx = x.m_timestamp_tx;
    m_data = x.m_data;
}

Payload::Payload(
        Payload&& x)
{
    m_sequence_number = x.m_sequence_number;
    m_timestamp_tx = x.m_timestamp_tx;
    m_data = std::move(x.m_data);
}

Payload& Payload::operator =(
        const Payload& x)
{

    m_sequence_number = x.m_sequence_number;
    m_timestamp_tx = x.m_timestamp_tx;
    m_data = x.m_data;

    return *this;
}

Payload& Payload::operator =(
        Payload&& x)
{

    m_sequence_number = x.m_sequence_number;
    m_timestamp_tx = x.m_timestamp_tx;
    m_data = std::move(x.m_data);

    return *this;
}

bool Payload::operator ==(
        const Payload& x) const
{

    return (m_sequence_number == x.m_sequence_number && m_timestamp_tx == x.m_timestamp_tx && m_data == x.m_data);
}

bool Payload::operator !=(
        const Payload& x) const
{
    return !(*this == x);
}

size_t Payload::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t Payload::getCdrSerializedSize(
        const Payload& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void Payload::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_sequence_number;
    scdr << m_timestamp_tx;
    scdr << m_data;

}

void Payload::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_sequence_number;
    dcdr >> m_timestamp_tx;
    dcdr >> m_data;
}

/*!
 * @brief This function sets a value in member sequence_number
 * @param _sequence_number New value for member sequence_number
 */
void Payload::sequence_number(
        uint32_t _sequence_number)
{
    m_sequence_number = _sequence_number;
}

/*!
 * @brief This function returns the value of member sequence_number
 * @return Value of member sequence_number
 */
uint32_t Payload::sequence_number() const
{
    return m_sequence_number;
}

/*!
 * @brief This function returns a reference to member sequence_number
 * @return Reference to member sequence_number
 */
uint32_t& Payload::sequence_number()
{
    return m_sequence_number;
}

/*!
 * @brief This function sets a value in member timestamp_tx
 * @param _timestamp_tx New value for member timestamp_tx
 */
void Payload::timestamp_tx(
        uint64_t _timestamp_tx)
{
    m_timestamp_tx = _timestamp_tx;
}

/*!
 * @brief This function returns the value of member timestamp_tx
 * @return Value of member timestamp_tx
 */
uint64_t Payload::timestamp_tx() const
{
    return m_timestamp_tx;
}

/*!
 * @brief This function returns a reference to member timestamp_tx
 * @return Reference to member timestamp_tx
 */
uint64_t& Payload::timestamp_tx()
{
    return m_timestamp_tx;
}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void Payload::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void Payload::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& Payload::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& Payload::data()
{
    return m_data;
}

size_t Payload::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Payload::isKeyDefined()
{
    return false;
}

void Payload::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
